version: "3.8"

services:
  python:
    build: .
    container_name: python3-server
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_ENV=${FLASK_ENV}

networks:
  ggg:
    