name: datathon

services:
  python:
    build: .
    container_name: python3-server
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_ENV=${FLASK_ENV}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - datathon
    volumes:
      - .:/app
    ports:
      - 5000:5000

  mongo:
    image: mongo:6.0
    #container_name: mongo-server
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - datathon

volumes:
  mongo_data:

networks:
  datathon:
    